### ISSUE TITLE
AS OF not applied to Related data

### ISSUE THREAD

**Issue by petarkekez** [Adam-Langley/efcore-temporal-query#1]
I am having an issue that the JOINS do not apply AS OF.

EF Core Query:
```
            var date = new DateTime(2020, 4, 29, 23, 0, 0);

            var customerRecord = _bla.Blogs
                .Include(x => x.Posts)
                .AsOf(date)
                .AsNoTracking()
                .ToList();
```

Profiler captured this query:
```
exec sp_executesql 
N'SELECT [b].[BlogId], [b].[Rating], [b].[Url], [p].[PostId], [p].[BlogId], [p].[Content], [p].[Title] 
FROM [Blogs] FOR SYSTEM_TIME AS OF @__ef_temporal__p_0 AS [b] 
  LEFT JOIN [Posts] AS [p] ON [b].[BlogId] = [p].[BlogId] 
ORDER BY [b].[BlogId], [p].[PostId]',N'@__ef_temporal__p_0 datetime2(7)',@__ef_temporal__p_0='2020-04-29 23:00:00'
```

The "AS OF" is missing after LEFT JOIN.
This means that the relations do not apply temporal data.

In the read.me it states:
"All joined relationships will have the FOR SYSTEM_TIME predicate applied to the generated SQL."

Any idea why this is happening?

**Comment by Adam-Langley** [comment]
Hi there @petarkekez,
Your usage scenario is quite simple - is it possible that you're using an internal service provider?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.useinternalserviceprovider?view=efcore-3.1#Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_UseInternalServiceProvider_System_IServiceProvider_

There are complexities in supporting internal service providers - hence the temporal registration extension method explicitly checks for it, and will not register in this case.

See `if (coreOptions.InternalServiceProvider == null)`

https://github.com/Adam-Langley/efcore-temporal-query/blob/master/src/EFCore.Temporal.Query/Extensions/SqlServerEntityTypeBuilderExtensions.cs

Note: if you have an internal service provider, calling `OptionsBuilder.ReplaceService` will throw an exception - hence why I avoid it.

**Comment by petarkekez** [comment]
The internal service provider is not used. 
i have c/p the code to OnConfiguring:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var coreOptions = optionsBuilder.Options.GetExtension<CoreOptionsExtension>();

            if (coreOptions.InternalServiceProvider == null)
            {
                optionsBuilder = optionsBuilder
                    // replace the service responsible for generating SQL strings
                    .ReplaceService<IQuerySqlGeneratorFactory, AsOfQuerySqlGeneratorFactory>()
                    // replace the service responsible for traversing the Linq AST (a.k.a Query Methods)
                    .ReplaceService<IQueryableMethodTranslatingExpressionVisitorFactory, AsOfQueryableMethodTranslatingExpressionVisitorFactory>()
                    // replace the service responsible for providing instances of SqlExpressions
                    .ReplaceService<ISqlExpressionFactory, AsOfSqlExpressionFactory>();
            }
        }
```
The **DbContextOptionsBuilder.UseInternalServiceProvider** is never used. When debugging the ReplaceService is executed correctly

**Comment by Adam-Langley** [comment]
Hi - and you have marked the entities as “temporal capable” with: 

modelBuilder.Entity<Customer>(b => {
    b.HasTemporalTable();
});

If you have followed these steps- the quickest solution is going to be a Skype/Teams video session where we can step through the temporal extensions source code. So if you can pull the code and get it running in your project, we can do a screen share. Let me know.

**Comment by ma-ed** [comment]
Hi,

I played a bit with this extension and came across the same unexpected behaviour. To me it seems like this does not work for collection navigation properties.

In a one-```Blog```-has-many-```Posts```-scenario this would work for this query
```csharp
var customerRecord = _bla.Posts
   .Include(x => x.Blog)
   .AsOf(date)
   .AsNoTracking()
   .ToList();
```

but not the other way around

```csharp
var customerRecord = _bla.Blogs
   .Include(x => x.Posts)
   .AsOf(date)
   .AsNoTracking()
   .ToList();
```

I realized that in the working case the method ```AsOfQueryableMethodTranslatingExpressionVisitor.TranslateJoin``` gets called but in the 1-to-many query no ```AsOfQueryableMethodTranslatingExpressionVisitor.TranslateXXX``` is called and therefore the ```AsOfDate``` of the second ```TableExpression``` ist ```null```.

I couldn't find any override that would possibly handle this case. Do you have an idea how this could be handled?

I would love to use this ef core extension in our project, but I'm kind of stuck right now.

**Comment by taconaut** [comment]
I can confirm above conclusion by @ma-ed

**Comment by taconaut** [comment]
I did some further analysis, to try understanding and hopefully fix the issue. For the example I've used this entity (only showing relevant navigation properties):
```
    public class PraeparatEntity : BaseEntity
    {
        public AdresseEntity Adresse { get; set; }

        public IEnumerable<PackungEntity> Packungen { get; set; }
    }
```
Working example when loading `Adresse` (showing `methodCallExpression.DebugView` from `AsOfQueryableMethodTranslatingExpressionVisitor.VisitMethodCall`):
```
.Call System.Linq.Queryable.Select(
    .Call Microsoft.EntityFrameworkCore.Internal.QueryableExtensions.LeftJoin(
        .Call Microsoft.EntityFrameworkCore.SqlServerQueryableExtensions.AsOf(
            .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.PraeparatEntity]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.PraeparatEntity]),
            $__p_0),
        .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.AdresseEntity]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.AdresseEntity]),
        '(.Lambda #Lambda1<System.Func`2[Refdata.SAI.Common.Entities.PraeparatEntity,System.String]>),
        '(.Lambda #Lambda2<System.Func`2[Refdata.SAI.Common.Entities.AdresseEntity,System.String]>),
        '(.Lambda #Lambda3<System.Func`3[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity,Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity]]>))
    ,
    '(.Lambda #Lambda4<System.Func`2[Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity],Refdata.SAI.Common.Entities.PraeparatEntity]>))

.Lambda #Lambda1<System.Func`2[Refdata.SAI.Common.Entities.PraeparatEntity,System.String]>(Refdata.SAI.Common.Entities.PraeparatEntity $e)
{
    .Call Microsoft.EntityFrameworkCore.EF.Property(
        $e,
        "Zulassungsinhaberin")
}

.Lambda #Lambda2<System.Func`2[Refdata.SAI.Common.Entities.AdresseEntity,System.String]>(Refdata.SAI.Common.Entities.AdresseEntity $a)
{
    .Call Microsoft.EntityFrameworkCore.EF.Property(
        $a,
        "PartnerNr")
}

.Lambda #Lambda3<System.Func`3[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity,Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity]]>(
    Refdata.SAI.Common.Entities.PraeparatEntity $o,
    Refdata.SAI.Common.Entities.AdresseEntity $i) {
    .New Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity](
        $o,
        $i)
}

.Lambda #Lambda4<System.Func`2[Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity],Refdata.SAI.Common.Entities.PraeparatEntity]>(Microsoft.EntityFrameworkCore.Query.TransparentIdentifierFactory+TransparentIdentifier`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.AdresseEntity] $e)
{
    .Extension<Microsoft.EntityFrameworkCore.Query.IncludeExpression>
}
```

Not working example when loading `Packungen`:
```
.Call System.Linq.Queryable.Select(
    .Call Microsoft.EntityFrameworkCore.SqlServerQueryableExtensions.AsOf(
        .Constant<Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.PraeparatEntity]>(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Refdata.SAI.Common.Entities.PraeparatEntity]),
        $__p_0),
    '(.Lambda #Lambda1<System.Func`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.PraeparatEntity]>))

.Lambda #Lambda1<System.Func`2[Refdata.SAI.Common.Entities.PraeparatEntity,Refdata.SAI.Common.Entities.PraeparatEntity]>(Refdata.SAI.Common.Entities.PraeparatEntity $e)
{
    .Extension<Microsoft.EntityFrameworkCore.Query.IncludeExpression>
}
```

We can see that no `LeftJoin`, but only a `Select` is being executed. As I understand it, the override of `TranslateSelect` is missing:
```
        protected override ShapedQueryExpression TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
        {
            if (source.TryGetDateParameter(out var asOfParameter))
            {
                // What to do here?
            }

            return base.TranslateSelect(source, selector);
        } 
```
But I haven't been able to figure out what/how has to be translated there. @Adam-Langley do you see what has to be done?

**Comment by Adam-Langley** [comment]
Hi @taconaut - I have had a look at this, and also reproduced the issue. The code was written to meet a specific need, hence the obvious lack of unit tests results in neglected scenarios. I will look into this, however time is rare these days...

**Comment by taconaut** [comment]
Hi @Adam-Langley. Debugging this issue was an interesting dive into expression transformations; I haven't had to dig this deep into EF core before. I hope you'll be able to fix this, as you have made an excellent job with this project.

**Comment by Adam-Langley** [comment]
Hi @taconaut - I've been away from this code for a while, and working on other things has given me a better understanding of the EF Core visitors. I think I have fixed the issue, resulting in a much simpler (and I think, correct) use of the MethodTranslatingExpressionVisitor.
Please try out the branch [defect/subqueries-not-transformed](https://github.com/Adam-Langley/efcore-temporal-query/tree/defect/subqueries-not-transformed) and let me know how this works for you.

**Comment by taconaut** [comment]
Hi @Adam-Langley that was quick :) Everything looks correct.

I've done some tests loading all (also nested) navigation properties. Here's the list for you to understand the nesting:
```
var includeProperties = new[]
                        {
                            nameof(PraeparatEntity.Adresse),
                            nameof(PraeparatEntity.Atc),
                            nameof(PraeparatEntity.Packungen),
                            $"{nameof(PraeparatEntity.Sequenzen)}.{nameof(SequenzEntity.Applikationsart)}",
                            $"{nameof(PraeparatEntity.Sequenzen)}.{nameof(SequenzEntity.Deklarationen)}.{nameof(DeklarationEntity.Stoff)}.{nameof(StoffEntity.Synonyme)}"
                        };
```

Every `FROM` (also nested) as well as `LEFT JOIN` includes a `FOR SYSTEM_TIME AS OF @__ef_temporal__p_0 AS [a]`. I haven't tested other joins.

Please consider the two PRs I've set up before publishing a new version.

Thanks a lot!
