### ISSUE TITLE
Requirement for IncludeAsOf

### ISSUE THREAD

**Issue by daz-codersoft** [Adam-Langley/efcore-temporal-query#5]
Hi Adam,

Firstly - awesome library!  Thanks for creating it and making it available.

I need to be able to do an Include As Of a particular date.

My scenario - I have questions and answers.  It's possible a question's text may change, but when I look at answers, I want to see the answer to the question *as it was worded when answered*.

    public class Question
    {
      public Guid id {get; set;}
      public string text {get; set;}
    }

    public class Response
    {
      public Guid id {get; set;}
      public Guid questionId {get; set;}
      public Question question {get; set;}
      public string response {get; set;}
      public DateTime submissionDateTimeUTC {get; set;}
    }

I want to be able to do something like:

    var responseWithQuestion=context.Responses
        .IncludeAsOf (x=>x.question, x=>x.submissionDateTimeUTC);

I know I could do it in 2 queries (one to get the submissionDateTimeUTC, and then use the "AsOf") but thought I'd ask if this is something you would consider worthwhile?

Thanks.

Darryl

**Comment by Adam-Langley** [comment]
Hi Darryl,

I think you've probably realised that my AsOf will affect the entire join, not just the included relationship - so it won't work for you if _both_ your tables are temporal. If only your Question table is temporal however - it should work.
The answer to your question depends on how you define 'worthwhile'. 
You've given an example of the syntactical simplification that temporal tables is designed to facilitate. It's not like temporal tables enable anything that wasn't possible before their invention - they just make it more succinct to achieve - which sounds like what you're after.

If, however, you're asking if you should get hung up on using temporal tables to achieve a performance optimisation of reducing your query load by 1 - for a simple view, I wouldn't no.
